services:
  agent:
    build: ./client
    #command: ["python", "./agent/agent.py"]
    command: ["uvicorn", "main:app", "--no-access-log", "--host", "0.0.0.0", "--port", "80"]
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - 80:80

  news_tools:
    build: ./tools/news